COLORTERM: truecolor
DISPLAY: /private/tmp/com.apple.launchd.iIqTyf9sXu/org.xquartz:0
HOME: /Users/abbieb
LANG: en_US.UTF-8
LOGNAME: abbieb
LSCOLORS: GxFxcxdxCxegedabagacad
OSLogRateLimit: '64'
PATH: /Users/abbieb/Documents/School/Grad/Spring2026/DSMC/maestro/bin:/opt/homebrew/opt/open-mpi/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/opt/homebrew/bin
PWD: /Users/abbieb/Documents/School/Grad/Spring2026/DSMC/HW1
SHELL: /bin/bash
SHLVL: '2'
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.U8bzkj5B5u/Listeners
TERM: xterm-256color
TERM_PROGRAM: Apple_Terminal
TERM_PROGRAM_VERSION: '465'
TERM_SESSION_ID: 4FB0B03A-35B5-49D2-96BF-44B348AA92D8
TMPDIR: /var/folders/0c/v517tndd03x8g9_yl3gzgy9h0000gn/T/
USER: abbieb
VIRTUAL_ENV: /Users/abbieb/Documents/School/Grad/Spring2026/DSMC/maestro
VIRTUAL_ENV_PROMPT: maestro
XPC_FLAGS: '0x0'
XPC_SERVICE_NAME: '0'
_: /usr/bin/nohup
__CFBundleIdentifier: com.apple.Terminal
__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
